### ISSUE TITLE
QUESTION: Usage on non-minio s3 servers and concurrency

### ISSUE THREAD

**Issue by neocox** [minio/warp#13]
Hi!

Is it possible to use Warp with other S3 servers than Minio?

Regarding concurrency when several hosts (s3 endpoints) are defined, how do you distribute the traffic? round robin?

Thanks!

**Comment by klauspost** [comment]
>Is it possible to use Warp with other S3 servers than Minio?

Yes, only the `-serverprof` parameter is MinIO specific.

> Regarding concurrency when several hosts (s3 endpoints) are defined, how do you distribute the traffic? round robin?

See https://github.com/minio/warp#multiple-hosts

By default the host with the least connections is selected. In case of a tie, the one least recent to finish a request is chosen. You can chose `-host-select=roundrobin` to do a simple roundrobin, but slow hosts will likely slow your benchmark down.

**Comment by kannappanr** [comment]
@neocox Closing this issue as answered. Please feel free to reach out to us if you have further questions
