### ISSUE TITLE
warp does not appear to support TLS, as implied by the documentation

### ISSUE THREAD

**Issue by beefsalad** [minio/warp#131]
To reproduce.
$ wget https://github.com/minio/warp/releases/download/v0.3.17/warp_0.3.17_Linux_x86_64.deb
$ sudo dpkg -i warp_0.3.17_Linux_x86_64.deb
$ warp --tls
Incorrect Usage. flag provided but not defined: -tls

I see tls is defined in flags.go, but the binary does not seem to be aware of it.

**Comment by klauspost** [comment]
You must supply a command, eg. `warp get --tls`
