### ISSUE TITLE
Warp Helm Chart: warp server pod is unable to connect to the warp client pods

### ISSUE THREAD

**Issue by khalsa-ji** [minio/warp#133]
**Problem:** When installing warp on top of a Kubernetes cluster with the help of its current helm chart, the warp server pod is not able to connect to the warp client pods.

**Warp server pod logs:**
```
warp: Connecting to ws://warp-0.warp.default.svc.cluster.local:7761/ws
warp: <ERROR> Connection failed:dial tcp: lookup warp-0.warp.default.svc.cluster.local on 10.x.y.z:53: no such host, retrying...

... [The above set of lines gets repeated for a total of 3 times and then, finally the below set of lines are printed.]

warp: Connecting to ws://warp-0.warp.default.svc.cluster.local:7761/ws
warp: <ERROR> Unable to send benchmark info to warp client: dial tcp: lookup warp-0.warp.default.svc.cluster.local on 10.x.y.z:53: no such host.
```

**Fix:** On investigating this issue, it has been found that the service created for warp clients does not specify any port for the same where the traffic should be received i.e. _7761_ (the default one). If we mention this port in the `service.yaml` template file, the issue gets fixed and the warp server pods are able to connect with the warp client pods.

**Comment by harshavardhana** [comment]
Closed by #134
