### ISSUE TITLE
Error while bench marking

### ISSUE THREAD

**Issue by bharathiraja29** [minio/warp#156]
**Operation**: Mixed
**Concurrency**: 100
**Object size**: 50MiB

Getting the below error when the benchmarking is around 90% completion. Happened continuously multiple times. 

> panic: internal error: so.PerSegDuration <= 0

> goroutine 7342 [running]:
> github.com/minio/warp/pkg/bench.Operations.Segment(0xc016c48000, 0x0, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x416675, 0x7f205929fd00, ...)
> 	github.com/minio/warp/pkg/bench/analyze.go:142 +0x972
> github.com/minio/warp/pkg/aggregate.Aggregate.func2(0xc0001b5220, 0x4, 0x5, 0xc000731200, 0x4, 0x4, 0xc017198e90, 0xc01f4ec780, 0xc01f4ec7a0, 0x2)
> 	github.com/minio/warp/pkg/aggregate/aggregate.go:191 +0x532
> created by github.com/minio/warp/pkg/aggregate.Aggregate
> 	github.com/minio/warp/pkg/aggregate/aggregate.go:164 +0x7a7

**Comment by klauspost** [comment]
@bharathiraja29 Could you supply the commandline used. I would also expect the benchmark data has been written to a `*.csv.zst` already - can you attach a failing sample?

**Comment by bharathiraja29** [comment]
Below is the command used.
`warp mixed --host=<host:port> --access-key=<access-key> --secret-key=<secret-key> --autoterm --concurrent=100 --obj.size=50MiB`

Here the .csv.zst file data. 

```
warp analyze warp-mixed-2021-01-04[011541]-58G4.csv.zst
1481 operations loaded... Done!
panic: internal error: so.PerSegDuration <= 0

goroutine 83 [running]:
github.com/minio/warp/pkg/bench.Operations.Segment(0xc001a6e000, 0x0, 0xe9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/minio/warp/pkg/bench/analyze.go:142 +0x972
github.com/minio/warp/pkg/aggregate.Aggregate.func2(0xc00007c0a0, 0x4, 0x5, 0xc00013d200, 0x4, 0x4, 0xc000028070, 0xc00148a3e0, 0xc00148a400, 0x2)
	github.com/minio/warp/pkg/aggregate/aggregate.go:191 +0x532
created by github.com/minio/warp/pkg/aggregate.Aggregate
	github.com/minio/warp/pkg/aggregate/aggregate.go:164 +0x7a7
```

**Comment by harshavardhana** [comment]
Please attach the csv.zst file here @bharathiraja29

**Comment by harshavardhana** [comment]
also what is your warp version?

**Comment by bharathiraja29** [comment]
[warp-mixed-2021-01-04[011541]-58G4.csv.zst.zip](https://github.com/minio/warp/files/5767579/warp-mixed-2021-01-04.011541.-58G4.csv.zst.zip)

Warp version:
`warp version 0.3.27 - a9cbd92`

**Comment by klauspost** [comment]
Thanks! I will take a look.

**Comment by klauspost** [comment]
@bharathiraja29 Fix linked above. But you should run your benchmarks longer.

Running with this big objects it cannot complete enough operations to have useful data. Basically no PUT operations complete within the time window since you have so big objects and so high concurrency.
