### ISSUE TITLE
Skipping LIST too few samples - clarification on what this means

### ISSUE THREAD

**Issue by gcbritt** [minio/warp#157]
No matter what parameters I use, I get this output after trying to run the "list" function of warp. I'm assuming I'm using it incorrectly, but I am following the docs as far as I can tell. Here is an example command that gives this output:

`./warp list --host 127.0.0.1:9000 --access-key minioadmin -secret-key minioadmin --objects 10000 --obj.size 128KB --concurrent 600`

I am running a basic, one drive standalone server.

**Comment by harshavardhana** [comment]
> No matter what parameters I use, I get this output after trying to run the "list" function of warp. I'm assuming I'm using it incorrectly, but I am following the docs as far as I can tell. Here is an example command that gives this output:

yes but the number of samples are not sufficient you need to run it for longer such as --duration 10m or --duration 15m

**Comment by gcbritt** [comment]
Hi @harshavardhana, just want to follow up on your suggestion. I have tried to run the benchmark above for up to 15 hours using `--duration` and I still get:

`Skipping LIST too few samples`

What it seems that list is doing is running put on `--objects` objects and then afterwards it encounters this error and does not seem to run list properly:

`unexpected object count`

Here is a screenshot of one of my benchmark results, you can see after putting 10000 objects warp just hangs on this error.

<img width="958" alt="list-error" src="https://user-images.githubusercontent.com/1497822/103818218-4a919900-5025-11eb-9bbd-52e471418243.PNG">

Am I doing something wrong? Any ideas? I am using the same command I showed above, varying the `--duration` does not seem to help.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana, just want to follow up on your suggestion. I have tried to run the benchmark above for up to 15 hours using `--duration` and I still get:

What is the server under use here? have you modified the listing code in the backend? @gcbritt

**Comment by gcbritt** [comment]
> What is the server under use here? have you modified the listing code in the backend? @gcbritt

The minIO server is hosted on a single standalone NVMe SSD which is local to the machine I am running warp on. I have not modified any of the code, I am using minIO/warp binaries for x86_64 from the latest releases here on Github.

I am running minIO/warp on an intel Xeon server platform, running Ubuntu 20.04.1 LTS. The machine has 252GB of RAM. 

Another error I encountered which I do not know if it is related: when trying to run the above command with a duration longer than 15 hours, I got an out-of-memory error and the kernel killed warp before the benchmark could complete (I had tried this because I thought maybe 15 hours was still not long enough).

There are no other workloads or benchmarks running on this machine besides minIO and warp.

**Comment by klauspost** [comment]
@gcbritt Seems like there are errors

**Comment by gcbritt** [comment]
@klauspost yes, it seems that github doesn't support .zst files for upload so I had to recompress as .zip. This is a shorter ~15 minutes run, but the error is still present in the .csv file:

[warp-list-2021-01-11[093802]-IgI6.csv.zip](https://github.com/minio/warp/files/5797306/warp-list-2021-01-11.093802.-IgI6.csv.zip)

**Comment by harshavardhana** [comment]
> Another error I encountered which I do not know if it is related: when trying to run the above command with a duration longer than 15 hours, I got an out-of-memory error and the kernel killed warp before the benchmark could complete (I had tried this because I thought maybe 15 hours was still not long enough).

This is because you ran warp for 15hrs it would buffer the results in memory and can run out of memory.

**Comment by gaowayne** [comment]
@harshavardhana 
I run this command, it only show me the put results, but no List result. I feel maybe a bug, why it always report too few samples, I already run 30 min.

===
root@sm152:/home/intel/wayne/miniobin# ./warp list --host 127.0.0.1:9000 --access-key minioadmin -secret-key minioadmin --objects 100000 --obj.size 256KB  --concurrent=1 --duration=30m --debug
warp: Benchmark data written to "warp-list-2021-01-11[172506]-2I1E.csv.zst"                                                                                             

Operation: PUT
* Average: 33.48 MiB/s, 137.12 obj/s

Throughput, split into 145 x 5s:
 * Fastest: 37.2MiB/s, 152.51 obj/s
 * 50% Median: 33.2MiB/s, 136.17 obj/s
 * Slowest: 31.4MiB/s, 128.72 obj/s

-------------------

Skipping LIST too few samples. Longer benchmark run required for reliable results.
warp: Cleanup Done.
====

**Comment by harshavardhana** [comment]
> I run this command, it only show me the put results, but no List result. I feel maybe a bug, why it always report too few samples, I already run 30 min.

The reason is warp thinks that there are no good samples to provide results from // cc @klauspost can explain more.

**Comment by klauspost** [comment]
There is a bug in the list implementation it seems.
