### ISSUE TITLE
Add json analysis  output option suitable for parsing with jq.

### ISSUE THREAD

**Issue by suykerbuyk** [minio/warp#163]
I've an ugly bit of bash script that can convert most of the `warp analyze` output into csv files suitable for importing into spreadsheets, but it would be much more robust and less error prone if the warp analyze output was in json.

#!/bin/bash

for OP in get put delete
do
        for TST in $(ls ${OP}*.zst)
        do
                prefix="$(echo $TST | sed 's/.csv.zst//g' | sed 's/-/, /g')"
                echo -n "$prefix, $TST, "; warp analyze $TST \
                | grep 'Operation:' -A 1 \
                | tail -1; done \
                | sed 's/* Average: //g'
        done
https://drive.google.com/file/d/1npvAAj7qb5GjQYJ_a5Znij4xN_n-PENQ/view?usp=sharing

A sample output file from the above script can be found here:
https://drive.google.com/file/d/1npvAAj7qb5GjQYJ_a5Znij4xN_n-PENQ/view?usp=sharing

**Comment by klauspost** [comment]
@suykerbuyk Use `--json` parameter, eg ` warp analyze --json after.csv.zst >analysis.json`
