### ISSUE TITLE
Objects being put into Noobaa bucket are not the correct size

### ISSUE THREAD

**Issue by delillol** [minio/warp#164]
Running warp with the following configuration:
----------------------------------------------
~# **warp -v**
warp version 0.3.40 - d3ee60c

~# **cat /etc/*release**
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"

Problem description:
----------------------
Not sure if this s3 benchmarking tool supports Noobaa, but I see the following issue when my testcase puts objects into the specified bucket on my cluster.   In this case, I am asking warp to put 1M objects, but they show up as size: 1001525.  Warp recognizes this when it runs the verify of the objects.  Don't know if this is an issue with warp, or if Noobaa is changing the size of the objects once the objects are ingested.

Here is the testcase and the errors returned:
---------------------------------------------
**warp mixed --access-key=$myAccessKey --secret-key=$mySecretKey --host=myMasterNode.fyre.com:31699 --obj.size=1M --duration=60s --analyze.dur=20s --noprefix --objects=50 --bucket=myTestBucket**
.
.
.
warp: <ERROR> unexpected download size. want:1000000, got:1001525                                             
warp: <ERROR> unexpected download size. want:1000000, got:1001525                                             
warp: <ERROR> unexpected download size. want:1000000, got:1001525                                             
warp: <ERROR> unexpected download size. want:1000000, got:1001525                                             
warp: <ERROR> unexpected download size. want:1000000, got:1001525
.
.
.

When listing files inside of the bucket, we can see that the sizes are, indeed, 1001525:
--------------------------------------------------------------------------------------
-rw-r--r-- 1 noob root 1001525 Feb  8 17:18 '4.pL2n7gvgD(Czm07B.rnd'
-rw-r--r-- 1 noob root 1001525 Feb  8 17:18 '2.3r0Uc)fTin2junpx.rnd'
-rw-r--r-- 1 noob root 1001525 Feb  8 17:18  3.Yaz4D7aa4qDegVjE.rnd
-rw-r--r-- 1 noob root 1001525 Feb  8 17:18  1.sMLgZplOW0fN3Wgy.rnd
-rw-r--r-- 1 noob root 1001525 Feb  8 17:18 '2.rV2185qa4zw)Y2LF.rnd'
-rw-r--r-- 1 noob root 1001525 Feb  8 17:18  3.J7AHn1Afb7V86Hjz.rnd

**Comment by harshavardhana** [comment]
> Not sure if this s3 benchmarking tool supports Noobaa, but I see the following issue when my testcase puts objects into the specified bucket on my cluster. In this case, I am asking warp to put 1M objects, but they show up as size: 1001525. Warp recognizes this when it runs the verify of the objects. Don't know if this is an issue with warp, or if Noobaa is changing the size of the objects once the objects are ingested.

This looks like a bug on the server side @delillol - we do not see this with AWS S3 or MinIO

**Comment by delillol** [comment]
Thank you for the quick response.  I will let our Noobaa development team know about this.

**Comment by dcarrion87** [comment]
@harshavardhana sorry to resurrect this post but do you know what this ended up being? 

We're seeing a similar issue with an S3 proxy.

**Comment by dcarrion87** [comment]
@delillol sorry to resurrect this one but do you know what it ended up being? We're seeing similar issue with an S3 proxy.

**Comment by delillol** [comment]
Hi Daniel. I never followed up on whether or not there was a fix for that issue. I had been running a very early version of an S3 protocol. For over a year now, I have been working on something else so not sure if anyone ever found a solution or a code fix. Sorry that I can't be more help.
