### ISSUE TITLE
Warp and data verification

### ISSUE THREAD

**Issue by delillol** [minio/warp#169]
This is a question regarding Warp's functionality - not a bug.

I have been running "warp mixed" tests to my system that is running minio.  Can you tell me if warp has the capability to do data verification?  For example, I cannot tell if the GETs that are being performed are actually checking the data integrity.

**Comment by harshavardhana** [comment]
GET always checks data integrity on server side @delillol that is the bed rock of MinIO server functionality.

**Comment by delillol** [comment]
I thought that it did.  I just didn't see anything talking about that in the README or in the stdout of my Warp executions.  Thank you @harshavardhana .

**Comment by harshavardhana** [comment]
@delillol if you have further questions please join our https://slack.min.io for real time discussions and if you are planning to use MinIO in production consider taking subscription https://min.io/pricing
