### ISSUE TITLE
Allow warp to have improved features to the test

### ISSUE THREAD

**Issue by idealtech-i3dlabs** [minio/warp#177]
I want to be able to run multiple warp(s) in parrallel from many different servers. When I try it, it tries to remove the previous bucket (which is already running).

Also, would it be possible to add a feature to specify an SSL loadbalancer endpoint as the target ? When I try I get:

warp mixed --host=https://myhost.mydomain.com --access-key=<key> --secret-key=<key>

_warp: <ERROR> Unable to create MinIO client. Endpoint url cannot have fully qualified paths._

**Comment by harshavardhana** [comment]
> warp mixed --host=https://myhost.mydomain.com --access-key= --secret-key=

warp mixed --host=myhost.mydomain.com --tls

**Comment by harshavardhana** [comment]
> I want to be able to run multiple warp(s) in parrallel from many different servers. When I try it, it tries to remove the previous bucket (which is already running).

You need to read about distributed benchmark https://github.com/minio/warp#distributed-benchmarking

**Comment by harshavardhana** [comment]
Since these are already supported closing.
