### ISSUE TITLE
Windows Binary install

### ISSUE THREAD

**Issue by dwkim922** [minio/warp#179]
I downloaded "warp_0.4.2_Windows_x86_64.zip" and ive received several warnings that it may be a dangerous file from chrome and windows defender. But me being dumb, i ignored everything and ran the program anyway. I saw a cmd window pop up for a a second and it disappeared and then nothing happened. Now im paranoid...

**Comment by harshavardhana** [comment]
warp.exe is a command-line tool you need to use C:\ or Powershell:\ to invoke it - it's not some desktop application. 

AFAICS what you saw is normal, nothing to be surprised about.
