### ISSUE TITLE
[Feature-request]stop while reach --objects value

### ISSUE THREAD

**Issue by TestMsr** [minio/warp#188]
in Get benchmark read same file with the page cache will effect result

**Comment by harshavardhana** [comment]
Why will the page cache affect?  Who is your server vendor? 

They should be using O_DIRECT for reads just like how MinIO implements.

**Comment by TestMsr** [comment]
minio gateway nas.


cmd:
./warp get --access-key=ak --secret-key=sk--region=us-east=1 --bucket=test --disable-multipart --obj.size=1024KB --duration=1m0s

----------------------------------------
Operation: PUT
* Average: 96.81 MiB/s, 99.14 obj/s

Throughput, split into 24 x 1s:
 * Fastest: 100.3MiB/s, 102.68 obj/s
 * 50% Median: 96.9MiB/s, 99.24 obj/s
 * Slowest: 91.6MiB/s, 93.75 obj/s

----------------------------------------
Operation: GET
* Average: 834.97 MiB/s, 855.01 obj/s

Throughput, split into 59 x 1s:
 * Fastest: 2613.5MiB/s, 2676.24 obj/s
 * 50% Median: 247.1MiB/s, 253.05 obj/s
 * Slowest: 106.5MiB/s, 109.08 obj/s

mount with nfs v4 defaults
the network limition is 1000Mbps between nas and minio


in nas mode,besides the page cache,nfs cashe itself.

so i wish warp can be used like fio,the size controls the whole job's goal,and runtime just used for timeout

**Comment by harshavardhana** [comment]
You can enable MINIO_FS_SYNC=on to enable uncached behavior for NFS backend.

warp is not meant to do that.

**Comment by TestMsr** [comment]
> You can enable MINIO_FS_SYNC=on to enable uncached behavior for NFS backend.
> 
> warp is not meant to do that.

@harshavardhana in my previous test ,i have already set MINIO_FS_OSYNC=on.
So i can only set --objects higher and tune down the duration now

by the way,in [https://github.com/minio/minio/issues/13306](url),there is no error rate shown by warp and the  error column is empty in the csv file
