### ISSUE TITLE
on Premise S3 does not support ?location call  - preparing server fails

### ISSUE THREAD

**Issue by holgerjakob** [minio/warp#208]
Dear all

I have an on premise S3 storage that does not support the ?location call.
This ends up in the following:
warp: Preparing server.
warp: <ERROR> Error preparing server. Get "http://s3-ch.onlineecs.com:443/new-bucket-8af82d7a/?location=": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x03\x00\x02\x02P".

Is there any way to get this call disabled or the response ignored?

Thanks a lot, Holger

**Comment by harshavardhana** [comment]
Please ask your vendor to support proper S3 APIs.
