### ISSUE TITLE
Cannot run benchmark

### ISSUE THREAD

**Issue by servergeeks** [minio/warp#209]
Hello everyone,

I'm trying to run a couple of benchmarks using warp on a 4 node cluster and it's not able to run for some reason.
I have tried using the latest release and no success for now.

I always get a 400 error, when executing warp mixed.... 

```
./warp mixed --host 1.1.1.1:9000 --access-key "minioadmin" --secret-key "test" --duration 120s --obj.size 64M --concurrent 64 --insecure --debug
```

And the response is the following:
```
warp: Preparing server.
warp: <ERROR> Error preparing server: 400 Bad Request
 (0) benchmark.go:163 cli.runBench(..)
 Release-Tag:(no tag) | Commit:(dev) | Host:blabla | OS:linux | Arch:amd64 | Lang:go1.17.8 | Mem:3.4 MB/16 MB | Heap:3.4 MB/7.8 MB.
```

**Comment by servergeeks** [comment]
Redacted.

**Comment by harshavardhana** [comment]
This is because you are attempting non-tls for TLS endpoint
