### ISSUE TITLE
Need support for passing --objects in put workload

### ISSUE THREAD

**Issue by vivekanandan-k-rh** [minio/warp#210]
**Description:**

Need support for passing --objects in warp put workload. As of now, support is available for passing --objects only in mixed workloads where the benchmark starts after dumping the number of objects mentioned with --objects. Put workload needs support for passing the number of objects to upload with benchmark happening.

**Comment by klauspost** [comment]
Benchmarks are defined by the time duration you want to run. I don't want a second termination parameter which will just make it confusing.

You can use GET benchmarks with a short duration. This will also record the time the upload took.
