### ISSUE TITLE
QUESTION : Usage on how to run warp "Distributed Benchmarking" on MinIO Nodes deployed on Kubernetes.

### ISSUE THREAD

**Issue by amirkool** [minio/warp#212]
Hi 

How can we run  warp "Distributed Benchmarking" on MinIO Nodes deployed on Kubernetes ?

For kubernetes MinIO deployment i have used the instructions available at https://github.com/minio/operator/blob/master/README.md
I have created 4 Servers MinIO node in kubernetes on which i want to start the warp "Distributed Benchmarking".
Please share the steps/instructions for the same. 

Thank you!

**Comment by klauspost** [comment]
See https://github.com/minio/warp/tree/master/k8s#running-warp-on-kubernetes
