### ISSUE TITLE
Max number of objects supported?

### ISSUE THREAD

**Issue by dblacknc** [minio/warp#215]
I am using Warp in K8s mode with 22 clients.   A mix test with total ~250M 4KB objects, or about 11.3M per client, appeared to normally finish the prepare phase in all client, then it just exited - nothing further in the log, and didn't move to the benchmark phase.   I can try looking at the code, and thought to ask - what's the expected max for the total object count and/or the per-client count?

**Comment by klauspost** [comment]
250M objects may run you out of memory. You will need a good deal of memory to deal with that many.

**Comment by harshavardhana** [comment]
warp is benchmarking tool not a data generation tool - if you wish to only generate data it must be either custom written or use some other tool to do so. 

warp has some amount of memory state that is not suitable to create 250M objects, it would have OOMed on the client side.
