### ISSUE TITLE
Feature request:  Could you please add lowerLimit for random object size? 

### ISSUE THREAD

**Issue by garyguo** [minio/warp#223]
Current warp supports upload an object by a range of random object size with both --obj.size and --obj.randsize. 
--obj.size = 3m # upperlimit
--obj.randsize   # random enabled
So, the range of object size is between 0 - 3m. 

Could you please add one more parameter --obj.lowsize <lower> combined with --obj.size <upper> and --obj.randsize to support a random object size range of **lower <= object size <= upper** ?

**Comment by harshavardhana** [comment]
@garyguo please send a PR we will happily accept it.

**Comment by harshavardhana** [comment]
This was fixed via https://github.com/minio/warp/pull/245 and released
