### ISSUE TITLE
Red error messages have a very low contrast

### ISSUE THREAD

**Issue by bluikko** [minio/warp#226]
The error messages with red background color have a very low contrast and are near-unreadable:
![image](https://user-images.githubusercontent.com/14869000/189568143-63d94fc0-13b4-4efc-8585-4259c166e0c9.png)

Suggest to set the foreground color to black to improve the contrast - or even better, don't mess with the background color and just print with red foreground color.

**Comment by klauspost** [comment]
Seems to be an environment specific problem:

![image](https://user-images.githubusercontent.com/5663952/189590820-91954dd8-a963-42b5-8bd1-62d65557f406.png)

**Comment by bluikko** [comment]
Interesting. So there should be no changes to the background color? I have not noticed this behavior on anything else before.
`warp` is being run inside `tmux` on an RHEL9 over PuTTy.

All of the "yellow error messages" have a yellow background instead of foreground; some of the "red error messages" do have red foreground and some have a red background.

**Comment by harshavardhana** [comment]
Just turn-off the terminal color you will be fine, it is a bit too much for this tool to satisfy all terminal variants and their display sequences.
