### ISSUE TITLE
Feature request: Could you please add CAfile or CApath flag ?

### ISSUE THREAD

**Issue by llchry** [minio/warp#231]
Currently warp supports TLS configuration. However, when TLS is enabled, no document describes how to configure the CA certificate. I checked the source code and found that only the default root certificate of the system is loaded. My method is to add my certificate to the /etc/ssl/certs/ca-bundle.trust.crt.
Could you please add the configuration to better specify the CA certificate ? 
Or add some documents

**Comment by harshavardhana** [comment]
Just use SSL_CERT_FILE supported via Go standard library.
