### ISSUE TITLE
Need some a minimal example on connecting to anything OTHER than Minio

### ISSUE THREAD

**Issue by russfellows** [minio/warp#233]
While the existing docs are sufficient for testing against Minio, they are non-existent for anything else.  How about a very simple example of puts or gets to AWS S3?  Although it should be straightforward, numerous errors are preventing this from working.

**Comment by harshavardhana** [comment]
warp was written primarily for MinIO and it serves that purpose. Everything else is the same just like you would use MinIO you can use the server name to be s3.amazonaws.com.

I don't know what more we can describe here.

**Comment by harshavardhana** [comment]
```
warp get --duration=3m --bucket mys3bucket --host=s3.amazonaws.com --access-key=aws-key --secret-key=aws-secret-key
```

Just this simple.

**Comment by russfellows** [comment]
Thank you.  Your example is close, but not correct.  We found that you also have to include the region, either with your --region flag, or encoded into the host string.  See below.

![Warp_working](https://user-images.githubusercontent.com/25020967/198364601-cdbf191b-f51e-4e8f-86ae-0d99e0ffc838.png)
