### ISSUE TITLE
The "warp --analyze" consumes excessive amounts of system RAM, resulting in failed analysis

### ISSUE THREAD

**Issue by russfellows** [minio/warp#238]
Warp’s processing of output zst files with the “—analyze” command requires up to 140X more system RAM than the size of the zst file.  For example, when processing a 1.1 GB zst file, the warp process consumes up to 150 GB of system RAM.  This is beyond being inefficient, making processing of large zst result files impossible on many systems. 

Additionally, due to these issues, combining results from multiple (say 10) clients is impossible unless your system has 2+TB of DRAM, which is impractical, even by todays standards.  Manually "adding" multiple client outputs together does not yield the same results, as it is impossible to add / average response time percentiles for 90th and 99th percentiles from multiple sources.  

Many suggestions come to mind on how to remedy this situation, but the authors of warp are likely better positioned to design a new processing methodology.  This behavior is VERY reproducible, occurring whenever processing files.

**Comment by klauspost** [comment]
@russfellows This is expected. You are welcome to contribute your own processing.

`--analyze.skip` and `--analyze.dur` allows you to segment your analysis. We do not have any plans to rewrite this behaviour.

**Comment by russfellows** [comment]
OK, I have written a utility to parse the results.  My version is faster, and consumes 30x times less memory.  

Using Warp analyze to process 588 files consumed 125 GB of DRAM and took 36 hours.

My version can run in parallel, and thus I can run parse the 588 files in under two hours while using less than 4 GB of DRAM.

If you desire, I can post my utility; however, it is written in Perl, not Golang.  

Cheers,

**Comment by klauspost** [comment]
@russfellows Sure. If you have it on a github repo I can link it from the README.
