### ISSUE TITLE
Request enhancement for "warp --analyze" , there is no object size included in output results

### ISSUE THREAD

**Issue by russfellows** [minio/warp#240]
There is no indication anywhere within the output files of what object size(s) were used when running warp.  Thus, if the user has not somehow recorded the object size(s) used when invoking warp, there is no way to know what those sizes are when examining either the text, or csv output.  

As a result, if running tens or hundreds of workloads via automation, this makes collecting and analyzing data impractical at best.

**Comment by klauspost** [comment]
Added object sizes to `--analyze.v` output when relevant and not already there.
