### ISSUE TITLE
Support Path-style access

### ISSUE THREAD

**Issue by NiklasRosenstein** [minio/warp#249]
Hi! Thanks for this neat tool! I have an S3 object storage that doesn't support the "Virtual-hosted-style" access method but only the "Path-style" access method. I couldn't find a way to make that work with Warp.

```
$ ./warp mixed --host=s3.example.org --access-key=... --secret-key=... --bucket mybucket
warp: Preparing server.                                                                                                                                                                                               
warp: <ERROR> Error preparing server: 302 Found.
$ ./warp mixed --host=s3.example.org/mybucket --access-key=... --secret-key=...
warp: <ERROR> Unable to create MinIO client. Endpoint url cannot have fully qualified paths.
```

I can use the bucket just fine with `mc` though.

**Comment by klauspost** [comment]
@NiklasRosenstein Host should not include the bucket.

Warp uses path style urls by default. 

The documentation has the rest: https://github.com/minio/warp#configuration

**Comment by harshavardhana** [comment]
> $ ./warp mixed --host=s3.example.org --access-key=... --secret-key=... --bucket mybucket
> warp: Preparing server.                                                                                                                                                                                               
> warp: <ERROR> Error preparing server: 302 Found.

Looks like you need to pass the region @NiklasRosenstein your server is returning 302 for path style requests.
