### ISSUE TITLE
How to test across multiple hosts with different keys

### ISSUE THREAD

**Issue by leichin** [minio/warp#254]
I checked the instructions for testing multiple endpoints with https://github.com/minio/warp#multiple-hosts, and it seems that it only allows for a single pair of access key and secret key to be used. Is there a way to test multiple endpoints with each of them having their own access key and secret key?

Such as `warp put ... --host=<host1>,<host2>,<host3> --access-key=<host1_key>,<host2_key>,<host3_key> --secret-key=...`
Thank you!

**Comment by klauspost** [comment]
You can run [benchmarks independently](https://github.com/minio/warp#manually-distributed-benchmarking) and [merge](https://github.com/minio/warp#merging-benchmarks) the results.

The `--sync-start` allows to synchronize the start time.
