### ISSUE TITLE
How to put objects with non-random data using obj.generator

### ISSUE THREAD

**Issue by a-out-10-2** [minio/warp#258]
There's a Warp option called `--obj.generator`. 

> --obj.generator value  Use specific data generator (default: "random")

It looks like this option only accepts tokens "random" or "csv". How can I utilize this option on the CLI? Can I pass-in my own CSV file to determines the data written for each Put object?

**Comment by harshavardhana** [comment]
What purpose does it add providing your own object?

**Comment by a-out-10-2** [comment]
@harshavardhana: The purpose is so that I can decide how compressible I want each put object.

Example:
- highly compressible objects: data all one value (zeros)
- partially compressible objects: data 50% one value, %50 another value (e.g. zeros and ones)

**Comment by harshavardhana** [comment]
For that warp is not the right tool, you should write that with your application and measure it. Warp won't really measure compression that happens on the server side.
