### ISSUE TITLE
Calculate response times using Time Series CSV Output

### ISSUE THREAD

**Issue by AdarshYajaman** [minio/warp#261]
Could you please let me know if its possible to calculate response times of each request made by WARP using the timeseries CSV output file ? This will be important to understand how each request type is performing over time. 

CSV headers - 
index,op,host,duration_s,objects_per_op,bytes,full_ops,partial_ops,ops_started,ops_ended,errors,mb_per_sec,ops_ended_per_sec,objs_per_sec,start_time,end_time

Command to generate CSV - warp analyze {inputFileName} --analyze.out=output.csv
warp version - 0.6.0

The start_time and end_time - time difference always results to 1 second for all requests and cannot be considered?

**Comment by klauspost** [comment]
@AdarshYajaman The only request time that makes sense is the average request time for the requests running in the segment, and overlapping requests being weighed by the overlap amount.

The raw data file contains all requests and you can map that data:
```
idx	thread	op	client_id	n_objects	bytes	endpoint	file	error	start	first_byte	end	duration_ns
0	1	PUT	PYJp	1	1000	http://127.0.0.1:9001	7j7NL)fh/1.jOg2xD0ymp2(mZ7z.rnd		2023-04-14T20:27:09.8327247+02:00		2023-04-14T20:27:09.8676634+02:00	34938700
1	8	PUT	PYJp	1	1000	http://127.0.0.1:9002	1l2w5SPX/1.QG9H8hJpbbS78v9l.rnd		2023-04-14T20:27:09.8332514+02:00		2023-04-14T20:27:09.8794931+02:00	46241700
```

Use `zstd -d FILE.csv.zst` to decompress the data.

**Comment by AdarshYajaman** [comment]
@klauspost Thank you, can this be achieved by using warp command itself? Or do i need to install zstd in my machine to decompress the data?
