### ISSUE TITLE
warp multipart seems to have issues, incorrect validation & errors

### ISSUE THREAD

**Issue by i-m-mj** [minio/warp#282]
Warp for multipart benchmark errors with incorrect size validation. There is no error in multipart upload but the Get validation seems wrong. Below test was run with 5MiB part size & 10000 parts, but the validation looks for one part size i.e. 5 MiB (5242880)

**Command executed**
warp multipart --host=x.x.x.x:<port> --access-key=<> --secret-key=<> --bucket=mpu_1.0_bucket --part.size=5MiB --parts=10000 --analyze.v --tls --insecure
warp: Preparing server.                                                                                                                                       
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                             
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: <ERROR> unexpected download size. want:5242880, got:52428800000                                                                                         
warp: Benchmark data written to "warp-multipart-2023-08-20[012006]-2iWE.csv.zst"                                                                              

----------------------------------------
Operation: PUT (10000). Ran 5m37s. Size: 5242880 bytes. Concurrency: 20.

**Comment by harshavardhana** [comment]
What is the server here @i-m-mj ?

**Comment by i-m-mj** [comment]
> 

@harshavardhana O sorry missed to mention that, its not MinIO server but a s3 compatible storage solution. It should behave the same across all s3 compatible Object storage right..?

**Comment by harshavardhana** [comment]
> @harshavardhana O sorry missed to mention that, its not MinIO server but a s3 compatible storage solution. It should behave the same across all s3 compatible Object storage right..?

Yes this is because they do not implement downloading via partNumber https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax

warp requires all S3 APIs are implemented @i-m-mj you need to ask your S3 compatible to vendor to implement these APIs.

**Comment by i-m-mj** [comment]
> > @harshavardhana O sorry missed to mention that, its not MinIO server but a s3 compatible storage solution. It should behave the same across all s3 compatible Object storage right..?
> 
> Yes this is because they do not implement downloading via partNumber https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax
> 
> warp requires all S3 APIs are implemented @i-m-mj you need to ask your S3 compatible to vendor implement these APIs.

Oh ya you are right, It slipped my mind, we already have an enhancement request to implement that. Thanks for jet speed responses. @harshavardhana I have couple more questions about warp, where can I get them answered..?

**Comment by harshavardhana** [comment]
> Oh ya you are right, It slipped my mind, we already have an enhancement request to implement that. Thanks for jet speed responses. @harshavardhana I have couple more questions about warp, where can I get them answered..?

You can ask them right here..

**Comment by i-m-mj** [comment]
@harshavardhana Thanks for quick responses. I missed to ask the questions I had, asking them now.

**Questions:**

1. The multipart command in warp seems limiting it creates only one MPU per benchmark test, can't I create multiple MPU per benchmark..? Did I missed something..?
2. When doing put with warp if the obj.size is bigger lets say 128MB or so does warp internally does mpu put..? If yes then how can I disable it..?

**Comment by harshavardhana** [comment]
> 1. The multipart command in warp seems limiting it creates only one MPU per benchmark test, can't I create multiple MPU per benchmark..? Did I missed something..?

It is meant to test `multipart` only - if you want to test many MPUs use `warp put`

> 2\. When doing put with warp if the obj.size is bigger lets say 128MB or so does warp internally does mpu put..? If yes then how can I disable it..?

You can disable via `--disable-multipart`
