### ISSUE TITLE
Determine the storage required for a specific test.

### ISSUE THREAD

**Issue by akshay8043** [minio/warp#283]
Hello everyone,

I'm currently in the process of running a test with the specifications outlined below:

Test Specifications:

Object Size: 100GB, 200GB, 300GB, 500GB, 1000GB.
Target: Object storage nodes – 5 nodes equipped with NVME storage (S3 compatible storage).
Source: Client systems (Centos clients) – 5 nodes.
Threads: Default of 20 in total, with 5 threads per node, making it 20 threads in total.
Duration: 10 minutes.
Method: GET
While attempting to execute the following command, I've encountered a significant delay during the stage preparation:

**_./warp get --duration=10m --warp-client=xx.xx.xx.xx:7761 --access-key=xxx --secret-key=xxxxxxxxxxxxxxxxxxxxxxxxxxx --obj.size xxxGB --concurrent 20 --host=XX.XX.XX.{AAA...CCC}:XXXX --bucket XXXgb-ABCD --benchdata XXXGB-ABCD | tee XXXGB-ABCD.out_**

For instance, during a recent test where I was performing a 500GB read operation on a 5-node object storage cluster, using 5 clients over a duration of 15 minutes, I noticed that the stage preparation was taking an extended period of time i.e. I waited overnight for atleast 10 hours but it was not stopping to create files and start the read test. I observed that the bucket size was approximately 180TB, and even then, the process was ongoing in terms of file creation and stage preparation before the actual test could commence.

I am seeking guidance on how I can estimate the necessary storage requirements prior to initiating the test. Having access to such calculations would provide me with a better understanding of whether the proposed test aligns with the available storage capacity.

Thank you for your assistance.

**Comment by klauspost** [comment]
As stated in the [documentation](https://github.com/minio/warp#get):

> By default, `--objects` objects of size `--obj.size` are uploaded before doing the actual bench.

> If versioned listing should be tested, it is possible by setting `--versions=n` (default 1), which will add multiple versions of each object and request individual versions.

So for each client you are running `--objects` x `--obj.size` x `--versions` are uploaded.

The actual benchmarks are limited by time, so probably it will not be able to complete even a single round of downloads before it terminates.

> 100GB, 200GB, 300GB, 500GB, 1000GB.

Testing more than 100GB is likely pointless. The speed will be the same for all of them. Even 10GB should be enough to see the speed.

**Comment by klauspost** [comment]
2. Yes. That is the - - objects parameter.
