### ISSUE TITLE
can surrport multi bucket?

### ISSUE THREAD

**Issue by lygn128** [minio/warp#299]
can surrport multi bucket? 
use hash to put data to multi  bucket?

**Comment by harshavardhana** [comment]
what difference will that make?

**Comment by lygn128** [comment]
when i use one bucket the cluster qps max 4000 while disk and cpu not high,  so i want  to try multle buckets can reach  a high qps?   the  storage cluster is minio, thank you very much.

**Comment by harshavardhana** [comment]
There is no such that two buckets will give you higher QPS, each bucket uses same hardware there is nothing more you will gain by WRITING to two buckets v/s same bucket.

**Comment by lygn128** [comment]
> There is no such that two buckets will give you higher QPS, each bucket uses same hardware there is nothing more you will gain by WRITING to two buckets v/s same bucket.

thank you very much.
i have another question:  when i use minio, can large directories（HDD disk， one directory have 1500000+  sub files or directories ） cause weak write or read performance？ thank you very much.

**Comment by harshavardhana** [comment]
HDDs cannot be use for IOPs intensive tasks. You need to move to NVMe for better performance.

**Comment by lygn128** [comment]
> HDDs cannot be use for IOPs intensive tasks. You need to move to NVMe for better performance.

thank you very much,   i  have a cluster which 600  hdd drivers(6 servers), but when  put 64K size file benchark, only get a  4000 qps bench result, cpu and memory and io is not high,  do you think 4000   qps is a  reasonable  result?  thank you very much!

**Comment by klauspost** [comment]
@lygn128 You can reach out on `hello@min.io` and we can help you assist with your benchmarking/setup.
