### ISSUE TITLE
Missing space between client listen address and "Listening on"

### ISSUE THREAD

**Issue by dlarge** [minio/warp#300]
Hello. I noticed that there's a space missing before the client listen address console output:
```
client1:~ # warp client client1:7761
warp: Listening onclient1:7761
````
Very minor thing.

**Comment by harshavardhana** [comment]
```
~ warp client localhost:7761
warp: Listening on localhost:7761
```

Don't see any such thing.

**Comment by klauspost** [comment]
Ah.. Forgot to update. Upstream fix: https://github.com/fatih/color/pull/228
