### ISSUE TITLE
warp analyze.v is existed or killed while processing the  large zst file.

### ISSUE THREAD

**Issue by vishwanathahiremath** [minio/warp#307]
While running the analyze.v command, the warp tool exited with below output.

_```
12221653 operations loaded... Done!
Killed
```_

**Comment by klauspost** [comment]
A) Get access to more RAM.

B)  Use `--analyze.limit=(operation count)`  and `--analyze.offset=(operation count)` to split analysis by only loading a subset 
of the operations.

C) [push data to influx](https://github.com/minio/warp?tab=readme-ov-file#influxdb-output) when running.

**Comment by vishwanathahiremath** [comment]
Thank you for the reply. It has worked.
