### ISSUE TITLE
when using multiple clients, all clients seem to try to create the target bucket

### ISSUE THREAD

**Issue by KasperJanssens** [minio/warp#31]
I start with an empty minio docker and start two clients like mentioned in the readme. Then I start the server, the server finds both clients but then fails a little time later with the error message :
`Stage failed. Client localhost:9091 returned error. Your previous request to create the named bucket succeeded and you already own it.`
But clients run on my localhost on different ports, just for testing purposes, not a real perf test yet. Is there some way to make sure that the bucket only gets created once? Or should I create the bucket myself manually first to avoid this?

Edit: I am under the impression it is somewhat racy, I tried to add some console logging to check what is going on and I got it working now, just by adding console logs. Something that rings a bell?

**Comment by klauspost** [comment]
Thanks for the report. 

I will investigate and create a fix.
