### ISSUE TITLE
Warp tool not exiting when Minio Cluster is full

### ISSUE THREAD

**Issue by dw-tester** [minio/warp#313]

**Comment by harshavardhana** [comment]
@dw-tester, please provide more details. We cannot imagine your requirement; our issues are not dart boards. Please follow some etiquette when reporting issues.

**Comment by dw-tester** [comment]
@harshavardhana Apologies for the error. Not sure how this posted, but issue with full description is in https://github.com/minio/warp/issues/314.

If I am missing anything, or should be filling out a template please let me know.
