### ISSUE TITLE
Warp tool not exiting when Minio Cluster is full

### ISSUE THREAD

**Issue by dw-tester** [minio/warp#314]
When running an extended warp workload, it is not exiting when encountering the following error
![Screenshot 2024-05-01 at 3 16 10 PM](https://github.com/minio/warp/assets/166762185/8bb59a32-2641-4ac9-a8d1-15eeb1669ca7)

The Warp server running the workload does not report any errors.
![Screenshot 2024-05-01 at 2 01 32 PM](https://github.com/minio/warp/assets/166762185/82816c62-a9bc-49b1-aa76-6c95222bcb54)

The behavior I would expect would be for Warp to exit once it encountered a "Storage Backend has reached minimum drive threashold" error

Setup:
1 warp server
- Image: minio/warp:latest 
- Deploy date: 2024-03-27

8 Warp Clients
- Image: minio/warp:latest 
- Deploy date: 2024-03-27 

4 Minio Nodes 
- Image: minio/minio:latest
- Deploy Date: 2024-03-27

Command line run by warp:
warp put --duration=100h --host=removed --analyze.v --concurrent=200 --storage-class=STANDARD --noclear --influxdb=http://removed:8086/warp/test?tag=bench_Firmware_put_7mb_EC-1_
8_Apr-24-2024_1_1 --benchdata=bench_Firmware_put_7mb_EC-1_8_Apr-24-2024_1_1.out --warp-client=removed

Edit: Adding Warp command line

**Comment by klauspost** [comment]
We don't exit on errors in the actual benchmark. We complete the benchmark and record the errors.

**Comment by dw-tester** [comment]
Understood Thank you very much
