### ISSUE TITLE
list bench error

### ISSUE THREAD

**Issue by T-TRz879** [minio/warp#322]
When i use this command `warp list --host 'ip' --access-key='ak' --secret-key='sk!' --bucket='bucket' --disable-sha256-payload=true --region='eu-central-1' --obj.size=1KiB --objects=10 --duration=10s --concurrent=20`

I have received this result.
<img width="697" alt="image" src="https://github.com/minio/warp/assets/50860504/2647edd8-0bd2-4dd3-bdeb-ac735c17376f">

version: 0.10.0 - 43aa399

**Comment by klauspost** [comment]
The objects are split in `concurrent` prefixes, so your parameters doesn't make sense. But I will make it a bit more proof against mistakes.

**Comment by T-TRz879** [comment]
enenen...
What mean? I cannot understand `parameters doesn't make sense`

**Comment by klauspost** [comment]
Read the [docs](https://github.com/minio/warp?tab=readme-ov-file#list). You can't divide 10 objects into 20 prefixes.
