### ISSUE TITLE
list file bucket failed

### ISSUE THREAD

**Issue by sushangjie** [minio/warp#328]
when i use warp list --host=host:port--access-key=ak--secret-key=sk--autoterm
meet error
First Errors:
 * http://host:port, 2024-07-30 15:15:24 +0800 CST: Unexpected object count, want 500, got 501
 * Because in the file bucket, directories are returned as objects.
 * pls help fix it

**Comment by klauspost** [comment]
Which S3 server are you benchmarking against?

**Comment by harshavardhana** [comment]
Closing as stale.
