### ISSUE TITLE
The config of '--disable-sha256-payload=true' in Multipart useless

### ISSUE THREAD

**Issue by T-TRz879** [minio/warp#329]
Here are the commands 
```
warp multipart --host 'xxx' --access-key='xxx' --secret-key='xxx' --bucket='test-warp' --disable-sha256-payload=true --region='eu-central-1' --part.size=5MiB  --parts=2 --duration=60s --concurrent=10
```

<img width="1556" alt="image" src="https://github.com/user-attachments/assets/5b8c48f9-49d5-400a-95a1-6a3ae7c89602">
<img width="613" alt="image" src="https://github.com/user-attachments/assets/dc1dba58-8c12-429c-b5a5-2a0cdada25d0">

**Comment by klauspost** [comment]
@T-TRz879 No need to ping. We'll get to your issue.

**Comment by T-TRz879** [comment]
sorry~
