### ISSUE TITLE
Good to have a option to specify the No. objects to list per op (Objects per operation)

### ISSUE THREAD

**Issue by vishwanathahiremath** [minio/warp#333]
Currently warp doesn't support the option to specify the number of objects per request. The object per operations is also vary between --objects

**Comment by klauspost** [comment]
> specify the number of objects per request

You can't do a `GetObject` request with multiple objects.

>  The object per operations is also vary between --objects

No. Only `delete` and `list` operate on multiple objects per operation.

**Comment by vishwanathahiremath** [comment]
@klauspost  I meant for warp operation  `list` object not for `Getobject `.
 
`Operation: LIST (20427). Ran 1m0s. Objects per operation: 250. Concurrency: 20.`  a
In the above example, The `Objects per operation` is varies based in `--object` and `--concurrent` in the warp run.
It will be a good to have option similar to `--batch`

**Comment by klauspost** [comment]
Why? Maybe if you wrote what you are trying to achieve, maybe that would help.
