### ISSUE TITLE
Need a tool can create graph after having result on analyze file

### ISSUE THREAD

**Issue by batamsieuhang** [minio/warp#336]
**Issue Title:** Graph Generation from File Analysis in Warp

Hi Warp team,

I've noticed the two graphs displayed in your documentation:

![Graph 1](https://github.com/user-attachments/assets/fb6676fa-5d60-4b22-9947-c6e933795805)
![Graph 2](https://github.com/user-attachments/assets/b7144a3e-0b97-41b5-996a-91e205719e28)

I was wondering if there is any tool or command within this project that can generate similar graphs from analyzed files. 

Thank you!

**Comment by harshavardhana** [comment]
It's gnuplot

**Comment by klauspost** [comment]
Actually used Google Sheets for this. 

Top one is just the output decompressed and imported as CSV. The second is using `warp analyze --analyze.out=time.csv ....`
