### ISSUE TITLE
Continuous memory increase on client causing OOM crashes

### ISSUE THREAD

**Issue by vkhacharia** [minio/warp#337]
Hey,

I run tests with below setup.
1. Start 4 instances in client mode in k8s cluster.
2. Every 2 mins I start a job with parameters `warp mixed --duration 30s --warp-client ceph-warp-light-{0...3}.ceph-warp.kube-prometheus.svc:7761 --concurrent 10 --obj.size 2MiB --tls --insecure --benchdata /var/run/warpbench.txt --storage-class STANDARD`
3. Push the output of `warp analyze` to prometheus pushgateway.

**Issue**
The memory usage on warp client pods keeps increasing and eventually crash with OOM Here is the memory usage graph for one of the clients for last few days

<img width="1768" alt="image" src="https://github.com/user-attachments/assets/4cae5a27-d43f-4fd5-a977-56eb811d5897">

**More Information**
Allocated Resources for clients: 
- cpu: request=3 limit=5
- memory: request=3Gi limit=5Gi
Allocated Resources for server: 
- cpu: request=50m limit=200m
- memory: request=500Mi limit=1Gi

**Comment by klauspost** [comment]
Don't use tiny pods or [push results to Influx](https://github.com/minio/warp?tab=readme-ov-file#influxdb-output).

**Comment by vkhacharia** [comment]
Sorry but I think the issue is misunderstood. The issue is the memory consumption keeps increasing for the pod that runs warp client. 
My question is if its a good idea to have clients running all the time and server triggering the tests on defined frequency?

**Comment by klauspost** [comment]
@vkhacharia So this is between different runs?

**Comment by vkhacharia** [comment]
No differences, its to get metrics at a regular frequency, yes I would like to use influxDB but I dint have enough patience and just used pushgateway instead.

**Comment by klauspost** [comment]
@vkhacharia What I am asking is whether the graph is from a single benchmark, or from several?

Memory *will* build up on a single benchmark. But it show reset when a second benchmark is started.

**Comment by vkhacharia** [comment]
aah now I understand. The graph is memory consumption based on kube-metric-server for the pod that runs warp client. The reset is restart of pod when it gets OOM killed

**Comment by klauspost** [comment]
@vkhacharia I presume it is just a single benchmark it is running. I checked the code and AFAICT the memory will reset when the client runs the next benchmark, so you just need to allocate bigger pods - run the benchmark for a short period - or use `--stress`, which doesn't record the data.
