### ISSUE TITLE
Checking of hosts availability should be done on clients, not on server

### ISSUE THREAD

**Issue by kiltum** [minio/warp#339]
I set testlab with next network scheme
```
server (10.0.0.1) --- (firewall limit to 10.0.1.0/24) --- clients (10.0.1.0/24) - hosts (10.0.2.0/24)
```
In other words, server can connect only to clients, and not to hosts.

When I try to run tests on server by `warp run test.yml`, I got next error: 

```
arp: <ERROR> Head "https://10.0.2.28/warp-benchmark-bucket/": dial tcp 10.0.2.28:443: i/o timeout
``` 

To check, I run the same command at any of clients and all passed nice (so I make assumption, that all ok with tests etc).

Will be very nice, if all preparing steps like creating test bucker, check availability, etc will be transferred from "server" code to "client" code.

**Comment by harshavardhana** [comment]
who is supposed to create the objects and run benchmarks then?

**Comment by kiltum** [comment]
As I understand, create objects should be done from clients instances. run benchmars too. 
server should only control clients.

**Comment by klauspost** [comment]
AFAICT it depends on the benchmark. Only multipart comes to mind, where the server needs to create the multipart object and distribute the upload ID - and running a server profile is also done locally.

Please provide your full repro case, if not a multipart benchmark, which is unlikely to change.
