### ISSUE TITLE
virtual-hosted-style option

### ISSUE THREAD

**Issue by LancGH** [minio/warp#346]
Hi!

It seems that binary warp does'nt support option related to the virtual-hosted-style requests, path-style only.
Do you have a plan to include this option in the future releases?
Or may be it can be changed somewhere in source code as workaround.

Thanks.

**Comment by klauspost** [comment]
Added in #347

**Comment by LancGH** [comment]
Thank's a lot!

**Comment by ADustyOldMuffin** [comment]
👋🏻 Hey @klauspost do you know when a release will be cut with this change?
