### ISSUE TITLE
How to provide  256-bit Advanced Encryption Standard for --encrypt

### ISSUE THREAD

**Issue by vishwanathahiremath** [minio/warp#355]
warp with --encrypt uses AES-128bit, is there a way to provide mention/provide the AES-256  similar to 'x-amz-server-side​-encryption​-customer-algorithm'

**Comment by harshavardhana** [comment]
> warp with --encrypt uses AES-128bit, is there a way to provide mention/provide the AES-256 similar to 'x-amz-server-side​-encryption​-customer-algorithm'

--encrypt uses AES256

**Comment by vishwanathahiremath** [comment]
The log, It shows cipher as AES128 when we used the --encrypt.
 
 tls_version="TLSv1.3" tls_cipher="TLS_AES_128_GCM_SHA256"

**Comment by harshavardhana** [comment]
> The log, It shows cipher as AES128 when we used the --encrypt.
> 
> tls_version="TLSv1.3" tls_cipher="TLS_AES_128_GCM_SHA256"

That's TLS - not server side encryption of objects.
