### ISSUE TITLE
Make bucket/prefix part of host definition

### ISSUE THREAD

**Issue by klauspost** [minio/warp#45]
Add bucket/prefix part of the --host parameter instead of separate. Make it mandatory.

Never clear anything at or below what is specified.

Buckets must be created before starting.

**Comment by suykerbuyk** [comment]
I hacked an approximation of the functionality here:
https://github.com/minio/warp/compare/master...suykerbuyk:master

**Comment by harshavardhana** [comment]
This is not needed anymore..
