### ISSUE TITLE
question - is it possible to continue testing with errors

### ISSUE THREAD

**Issue by KasperJanssens** [minio/warp#61]
Hi, I am trying to find the maximum performance of a system under several object sizes. The system protects itself rather aggressively by sending 503s as soon as it starts getting flooded. The problem is that the benchmark clients interpret this as a fatal error and I do not even have a report at the end it seems. Is there some way I can configure the load tester to still provide me with a decent report, e.g. mentioning the error rate or so, so I can get an idea of the performance of the system?

**Comment by harshavardhana** [comment]
Good idea, we will get back.

**Comment by klauspost** [comment]
@KasperJanssens The benchmark will only exit, if the errors occur in preparation stage. If they occur during the actual run the errors will be recorded and the benchmark will continue.

I believe the client will even automatically retry with some backoff, so you are seeing serious errors.

**Comment by klauspost** [comment]
So if you are experiencing errors with `get` benchmarks, try using `put` instead which doesn't need any preparation.

**Comment by KasperJanssens** [comment]
It seems to be that the system is not ready after it booted up, or that is my hypothesis, because indeed, I have no issues during a put benchmark. I'll close the ticket for now, might reopen it later if I really find something worth mentioning concerning Warp. Thanks for the help.
