### ISSUE TITLE
Question - Is it possible to pass the name of the zst file to the benchmark

### ISSUE THREAD

**Issue by KasperJanssens** [minio/warp#65]
I was browsing through the options for warp and for warp put but I don't see the option. It would be good to be able to pass a name to my benchmark as I run a lot one after the other, unattended. It is of course possible to correlate them afterwards, but it would improve my quality of life if I could name them explicitly. Maybe it already exists and I am overlooking something?

**Comment by harshavardhana** [comment]
have you not seen `--benchdata` ?

**Comment by KasperJanssens** [comment]
I likely have not as I was looking for something like output file or output
name or so. I'll check it as soon as I am back in front of a computer and
close the ticket. Thanks.

**Comment by KasperJanssens** [comment]
That was it, I overlooked the option indeed, sorry about that, thanks for the answer.
