### ISSUE TITLE
fail to parse distribution options

### ISSUE THREAD

**Issue by igomura** [minio/warp#82]
In mixed test mode any distributions option below leads to failure

```
$ ./warp mixed \
        --warp-client worker1:80,worker2:80 \
        --access-key "warp" \
        --secret-key "warp123" \
        --host node{01...16}.dev.net:9000 --tls \
        --duration 5m \
        --concurrent 32 \
        --obj.size 10m \
        --obj.randsize \
        --get-distrib 6 \
        --put-distrib 10 \
        --stat-distrib 1 \
        --delete-distrib 1

warp: <ERROR> Error running remote benchmark: unhandled flag type: cli.Float64Flag.
```

**Comment by harshavardhana** [comment]
which version of warp are you running @igomura ?

**Comment by igomura** [comment]
I've build from HEAD. Commit 03fe1e2a

**Comment by harshavardhana** [comment]
> ```
> warp: <ERROR> Error running remote benchmark: unhandled flag type: cli.Float64Flag.
> ```

Looks like there is a build issue on your end @igomura please use the released binaries.

**Comment by igomura** [comment]
It is the same with released binaries.

$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

SELinux enforced

**Comment by harshavardhana** [comment]
Strange can't reproduce it at all @igomura ..

**Comment by klauspost** [comment]
I can repro. Let me see if I can fix it.
