### ISSUE TITLE
Cleanup after test takes very long time

### ISSUE THREAD

**Issue by igomura** [minio/warp#83]
I run a distributed test where I fill cluster of 16 nodes with data. I've noticed what it takes ~5min to push 120Gb of data to the cluster, but it takes more than hour to cleanup after test.
From metrics I can guess what workers use parallel threads to do PUTs but only single thread used for data removal.

**Comment by harshavardhana** [comment]
@igomura what was the average size of the objects?

**Comment by harshavardhana** [comment]
NOTE: you can use --noclear to avoid cleanup stage.

**Comment by igomura** [comment]
The object size was 1M or less
