### ISSUE TITLE
Capture all command line options in warp output files

### ISSUE THREAD

**Issue by eco-minio** [minio/warp#94]
Consider a sample command line to initiate warp:
`./warp get --access-key minio --secret-key minio123 --tls  --host minio0{1...4}:9000 --warp-client warp-client{1...4} --duration 5m --objects 500 --obj.size 1MB --concurrent 32`

Analyze output shows the following:
`Operation: GET. Concurrency: 128. Hosts: 4. * Average: 3316.29 MiB/s, 3477.39 obj/s (4m59.873s, starting 17:44:12 UTC)`

So I see concurrency and hosts, but I don't know if it was a TLS connection, how many objects or duration, these are helpful to know what options are used in a given warp run, and esp. helpful for knowing what to run `cmp` against.

**Comment by harshavardhana** [comment]
Nice idea @eco-minio we should

**Comment by klauspost** [comment]
This could be added as comment fields in the CSV.

**Comment by klauspost** [comment]
Implementing, but finding some way to filter the access/secret key. I want it to be 'safe' to share the benchmark data.
